fail_fast: false
repos:
- repo: https://github.com/pocc/pre-commit-hooks
  rev: master
  hooks:
  - id: clang-format
    args: ["--style={BasedOnStyle: Google, IndentWidth: 4}"]
    files: ^src/
  - id: clang-tidy
    files: ^src/
  # - id: oclint
  #   files: ^src/
  - id: uncrustify
    files: ^src/
  - id: cppcheck
    files: ^src/
  - id: cpplint
    files: ^src/
  # - id: include-what-you-use
  #   files: ^src/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
