# Work around for virtualenv with python=3.10
# https://github.com/pre-commit/pre-commit/issues/1375
default_language_version:
  python: python3

fail_fast: false
repos:
- repo: https://github.com/Takishima/cmake-pre-commit-hooks
  rev: v1.5.3
  hooks:
    - id: clang-format
      args:
        - '-B_build-pre-commit'
        - '-DSPGLIB_WITH_Fortran=ON'
        - '-DSPGLIB_WITH_TESTS=ON'
        - '-i'
      exclude: src/msg_database.c
    - id: clang-tidy
      args:
        - '-B_build-pre-commit'
        - '-DSPGLIB_WITH_Fortran=ON'
        - '-DSPGLIB_WITH_TESTS=ON'
      exclude: src/msg_database.c

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    files: python/
    args:
    - "--max-line-length=88"
    - "--ignore=E203,W503"

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    files: python/
    args:
    - --line-length=88

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    files: python/spglib
    additional_dependencies: ["toml"]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      files: python/
      args: ["--profile", "black"]
