name: spglib test using conda

on:
  push:
    branches-ignore:
      - rc
      - master
  pull_request:
    branches: [develop]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install --yes -c conda-forge python=3.9
        conda install --yes -c conda-forge numpy gcc_linux-64 pip pytest codecov pytest-cov pyyaml
    - name: Setup spglib
      working-directory: ./python
      run: |
        ./get_nanoversion.sh
        cat __nanoversion__.txt
        python setup.py build
        pip install -e .
    - name: Test with pytest
      working-directory: ./python
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        verbose: true

  c-test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install --yes -c conda-forge python=${{ matrix.python-version }}
        conda install --yes -c conda-forge gcc_linux-64 make cmake
    # Require CMake>=3.14 for the following build procedure
    - name: Test
      run: |
        cmake -S . -B build -DUSE_SANITIZER="Address"
        cmake --build build -t check

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda install --yes -c conda-forge python=3.9
        conda install --yes -c conda-forge numpy gcc_linux-64 pip pyyaml

    - name: Setup spglib with doc's dependencies
      working-directory: ./python
      run: |
        python -m pip install -e .[doc]

    - name: Build
      run: |
        sphinx-build doc docs_build

    - name: Deploy docs at develop branch
      if: ${{ github.ref == 'refs/heads/develop' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs_build
        destination_dir: develop
